"""Command-line interface: `datadoctor <command>` (also `python tools/oah_audit.py`)."""

from __future__ import annotations

import argparse
import asyncio
import json
import math
import random
import sys
from pathlib import Path
from typing import Any

from datadoctor.audit.service import AuditResult, run_audit
from datadoctor.config import REPO_ROOT, get_settings
from datadoctor.domain.enums import Scope, Severity
from datadoctor.domain.models import Dataset, Finding
from datadoctor.ingestion.cache import HttpCache
from datadoctor.ingestion.fhir_client import FhirClient
from datadoctor.ingestion.snapshot import create_snapshot, list_snapshots, verify_snapshot
from datadoctor.knowledge.loader import load_knowledge

STATS = "http://terminology.hl7.org/CodeSystem/observation-statistics"


def _print_summary(res: AuditResult) -> None:
    s = res.summary
    src = res.source
    label = f"LIVE {src.fetched_at}" if src.kind.value == "live" else f"SNAPSHOT {src.snapshot_id} (sha256 {str(src.manifest_sha256)[:12]})"
    print(f"\nOAH Data Doctor — run {res.run_id}")
    print(f"source      : {label}  {src.base_url}")
    if src.fallback_reason:
        print(f"FALLBACK    : {src.fallback_reason}")
    print(f"resources   : {s.resources_by_type}  scope={s.resources_by_scope}")
    print(f"findings    : {s.findings_total}  {s.findings_by_severity}  scope={s.findings_by_scope}")
    print(f"integrity   : {s.oah_observations - s.oah_observations_with_blocking}/{s.oah_observations} OAH observations "
          f"free of ERROR/CRITICAL findings ({(s.integrity_pass_rate or 0) * 100:.1f}%)")
    print("by rule     :")
    for rid, n in s.findings_by_rule.items():
        print(f"   {rid:16s} {n}")
    a = s.anchor
    print(f"anchor      : {a['id']} present={a['present']} values={a.get('values')} unit={a.get('unit')} rules={a['rules_fired']}")


def _raw_stats(raw: dict[str, Any] | None) -> dict[str, float]:
    v: dict[str, float] = {}
    for c in (raw or {}).get("component", []):
        for cc in c.get("code", {}).get("coding", []):
            if cc.get("system") == STATS and "valueQuantity" in c and c["valueQuantity"].get("value") is not None:
                v[cc["code"]] = float(c["valueQuantity"]["value"])
    return v


def _independent_check(f: Finding, ds: Dataset) -> str:
    """Re-derive a finding directly from the raw JSON with separate, deliberately naive code (no tolerances,
    no rule helpers). A pre-review aid for the human reviewer, not a substitute for judgement."""
    raw = ds.raw.get(f.resource.resource_type, {}).get(f.resource.resource_id)
    v = _raw_stats(raw)
    mn, mx, av, md, sd = (v.get(k) for k in ("minimum", "maximum", "average", "median", "std-dev"))
    try:
        if f.rule_id == "SEM-STAT-001":
            ok = not (mn <= md <= mx)  # type: ignore[operator]
        elif f.rule_id == "SEM-STAT-002":
            ok = not (mn <= av <= mx)  # type: ignore[operator]
        elif f.rule_id == "SEM-STAT-003":
            ok = abs(av - md) > sd  # type: ignore[operator]
        elif f.rule_id == "SEM-STAT-004":
            ok = sd > (mx - mn) / math.sqrt(2)  # type: ignore[operator]
        elif f.rule_id == "SEM-STAT-005":
            ok = mn > mx  # type: ignore[operator]
        elif f.rule_id == "SEM-SCALE-001":
            ok = max(av / md, md / av) >= 100  # type: ignore[operator]
        elif f.rule_id == "SEM-RANGE-001":
            b = f.evidence.measures.get("bounds", {})
            vals = [o.value for o in f.evidence.observed if isinstance(o.value, (int, float))]
            ok = bool(vals) and all((("min" in b and x < b["min"]) or ("max" in b and x > b["max"])) for x in vals)
        elif f.rule_id == "SEM-XREC-001" and f.related_resources:
            sup = _raw_stats(ds.raw["Observation"].get(f.related_resources[0].resource_id))
            ok = any(v.get(k) is not None and sup.get(k) is not None and v[k] > sup[k] for k in ("average", "median", "maximum"))
        else:
            return "n/a (rule without a closed-form re-check: review the evidence)"
    except (TypeError, ZeroDivisionError):
        return "n/a (statistic missing)"
    return "CONFIRMED (raw values violate the constraint)" if ok else "NOT CONFIRMED — review carefully"


def _gate0_report(res: AuditResult, ds: Dataset, seed: int, n: int) -> str:
    s = res.summary
    oah = [f for f in res.findings if f.scope is Scope.OAH_IG]
    blocking = [f for f in oah if f.severity in (Severity.ERROR, Severity.CRITICAL)]
    distinct_resources = {f.resource.key for f in blocking}
    rng = random.Random(seed)
    sample = rng.sample(res.findings, min(n, len(res.findings)))
    lines = [
        "# Gate 0 report",
        "",
        f"Generated by `datadoctor gate0` — run `{res.run_id}` — {res.created_at}.",
        "",
        "## Source",
        "",
        f"- Kind: **{res.source.kind.value}**; base URL `{res.source.base_url}`; fetched at **{res.source.fetched_at}**"
        + (f"; snapshot `{res.source.snapshot_id}` (manifest sha256 `{res.source.manifest_sha256}`)" if res.source.snapshot_id else ""),
        f"- Rules version `{res.rules_version}`, knowledge version `{res.knowledge_version}`, IG source commit `{res.ig_commit[:12]}`.",
        "",
        "## Resources fetched by type",
        "",
        "| Type | Count |", "|---|---|",
        *[f"| {t} | {c} |" for t, c in s.resources_by_type.items()],
        "",
        f"Scope: {s.resources_by_scope} (oah-ig = ids defined as examples in the OAH IG source; third-party = written to the shared sandbox by others).",
        "",
        "## Findings by rule and severity",
        "",
        "| Rule | Findings |", "|---|---|",
        *[f"| {r} | {c} |" for r, c in s.findings_by_rule.items()],
        "",
        f"By severity: {s.findings_by_severity}. By scope: {s.findings_by_scope}.",
        "",
        "## Anchor record",
        "",
        f"`Observation/{s.anchor['id']}` present: **{s.anchor['present']}**. Live values (verbatim): `{json.dumps(s.anchor.get('values'))}` "
        f"unit `{s.anchor.get('unit')}`. Rules fired: {', '.join(s.anchor['rules_fired']) or 'none'}.",
        "",
        "## Gate criterion",
        "",
        f"- Distinct OAH-IG resources with at least one ERROR/CRITICAL finding: **{len(distinct_resources)}** (threshold: >= 10).",
        f"- ERROR/CRITICAL findings on OAH-IG resources: **{len(blocking)}**.",
        "- Human review of the random sample below is REQUIRED before GO (>= 80 % true positives).",
        "",
        f"## Random sample of {len(sample)} findings (seed {seed})",
        "",
        "Each entry prints the raw evidence. `Independent re-derivation` recomputes statistical constraints directly from "
        "the raw JSON with separate code; it is a pre-review aid, not a substitute for human judgement.",
        "",
    ]
    for i, f in enumerate(sample, 1):
        lines += [
            f"### {i}. {f.rule_id} · {f.severity.value} · confidence {f.confidence} · {f.scope.value}",
            "",
            f"**Resource:** `{f.resource.key}`" + (f" at `{f.resource.fhir_path}`" if f.resource.fhir_path else ""),
            "",
            f"**Summary:** {f.summary}",
            "",
            f"**Constraint:** `{f.evidence.constraint}`",
            "",
            "**Observed:** " + "; ".join(f"{o.label} = {o.value}{(' ' + o.unit) if o.unit else ''}" for o in f.evidence.observed[:8]),
            "",
            f"**Independent re-derivation:** {_independent_check(f, ds)}",
            "",
        ]
        if f.lineage:
            lines += [f"**Upstream lineage:** {f.lineage.statement}  ", f"`{f.lineage.raw_row}`", ""]
        if f.evidence.raw_excerpt is not None:
            lines += ["<details><summary>Raw FHIR excerpt</summary>", "", "```json",
                      json.dumps(f.evidence.raw_excerpt, indent=1, ensure_ascii=False)[:2500], "```", "</details>", ""]
        lines += ["**Human verdict:** [ ] true positive  [ ] false positive  — reviewer: ______", ""]
    lines += ["## Sign-off", "", "- [ ] A human reviewed the sample above; true-positive rate: ____ / " + str(len(sample)),
              "- [ ] GO  /  [ ] STOP", "", "Reviewer: ____________________  Date: __________", ""]
    return "\n".join(lines)


async def _cmd_snapshot(args: argparse.Namespace) -> None:
    st = get_settings()
    kn = load_knowledge(st.knowledge_dir)
    cache = HttpCache(st.db_path, st.cache_ttl_s)
    base = "http://hl7.eu/fhir/ig/oah/StructureDefinition/"

    def validate(rtype: str, res: dict[str, Any]) -> bool:
        if args.no_validate:
            return False
        return rtype == "Observation" and res["id"] in kn.ig_instances and any(
            p.startswith(base) for p in res.get("meta", {}).get("profile", []))

    async with FhirClient(st.fhir_base, cache, delay_s=st.http_delay_s, timeout_s=st.http_timeout_s) as client:
        root = await create_snapshot(client, st.snapshots_dir, st.ingest_types, page_size=st.page_size,
                                     validate=validate, ig_commit=kn.ig_commit, knowledge_version=kn.version)
    cache.close()
    print(f"snapshot written: {root}")
    print(json.dumps(json.loads((root / 'manifest.json').read_text(encoding='utf-8'))["resource_counts"]))


async def _cmd_audit(args: argparse.Namespace) -> tuple[AuditResult, Dataset]:
    st = get_settings()
    res, ds = await run_audit(st, args.source, args.snapshot_id)
    _print_summary(res)
    out = Path(args.out) if args.out else st.reports_dir / res.run_id
    out.mkdir(parents=True, exist_ok=True)
    (out / "audit.json").write_text(res.model_dump_json(indent=1), encoding="utf-8")
    print(f"\nfindings written: {out / 'audit.json'}")
    return res, ds


async def _cmd_gate0(args: argparse.Namespace) -> None:
    res, ds = await _cmd_audit(args)
    report = _gate0_report(res, ds, args.seed, args.sample)
    target = REPO_ROOT / "docs" / "GATE0_REPORT.md"
    target.write_text(report, encoding="utf-8")
    print(f"gate 0 report: {target}")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="datadoctor", description="OAH Data Doctor — scientific integrity auditor")
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("snapshot", help="fetch everything from the live sandbox into data/snapshots/<utc>/")
    p.add_argument("--no-validate", action="store_true", help="skip server-side $validate of OAH observations")
    for name in ("audit", "gate0"):
        p = sub.add_parser(name)
        p.add_argument("--source", choices=["live", "snapshot", "auto"], default=None)
        p.add_argument("--snapshot-id", default=None)
        p.add_argument("--out", default=None)
        if name == "gate0":
            p.add_argument("--seed", type=int, default=20260930)
            p.add_argument("--sample", type=int, default=20)
    p = sub.add_parser("verify-snapshot")
    p.add_argument("snapshot_id", nargs="?")
    sub.add_parser("snapshots")
    args = ap.parse_args(argv)

    if args.cmd == "snapshot":
        asyncio.run(_cmd_snapshot(args))
    elif args.cmd == "audit":
        asyncio.run(_cmd_audit(args))
    elif args.cmd == "gate0":
        asyncio.run(_cmd_gate0(args))
    elif args.cmd == "snapshots":
        print(json.dumps(list_snapshots(get_settings().snapshots_dir), indent=1))
    elif args.cmd == "verify-snapshot":
        st = get_settings()
        snaps = list_snapshots(st.snapshots_dir)
        sid = args.snapshot_id or (snaps[0]["snapshot_id"] if snaps else None)
        if not sid:
            print("no snapshots")
            return 1
        problems = verify_snapshot(st.snapshots_dir / sid)
        print(f"{sid}: {problems if problems else 'OK, every file matches its sha256'}")
        return 1 if problems else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
